# Generated by Django 4.0.4 on 2022-04-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='covid',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
